---
version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr
    env_file: "./defaults.env"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
    volumes:
      - ${APP_VOLUME}/sonar/config: config
      - ${MEDIA_DIR}/tv:/tv
      - ${MEDIA_DIR}/anime:/anime
      - ${DOWNLOAD_DIR}/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  sabnzbd:
    image: linuxserver/sabnzbd
    env_file: "./defaults.env"
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${APP_VOLUME}/sabnzbd/config:/config
      - ${DOWNLOAD_DIR}/complete:/downloads
      - ${DOWNLOAD_DIR}/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    env_file: "./defaults.env"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
    volumes:
      - ${APP_VOLUME}/radarr/config:/config
      - ${MEDIA_DIR}/movies:/movies
      - ${DOWNLOAD_DIR}/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    env_file: "./defaults.env"
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ${APP_VOLUME}/transmission/config:/config
      - ${DOWNLOAD_DIR}/complete:/downloads
      - ${DOWNLOAD_DIR}/incomplete:/incomplete
      - ${DOWNLOAD_DIR}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    env_file: "./defaults.env"
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
      - PLEX_CLAIM=claim-ff-x-xYGjXmkkHZDASmH
    volumes:
      - ${APP_VOLUME}/plex/config:/config
      - ${MEDIA_DIR}/tv:/tv
      - ${MEDIA_DIR}/anime:/anime
      - ${MEDIA_DIR}/movies:/movies
    restart: unless-stopped
  nginx:
    image: nginx
    env_file: "./defaults.env"
    container_name: nginx
    volumes:
      - ${APP_VOLUME}/nginx/config:/etc/nginx/conf.d
      - ${APP_VOLUME}/certbot/config:/etc/letsencrypt
      - ${APP_VOLUME}/certbot/data:/var/lib/letsencrypt
    ports:
      - "443:443"
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certbot
    env_file: "./defaults.env"
    image: certbot/dns-digitalocean
    restart: unless-stopped
    volumes:
      - ${APP_VOLUME}/certbot/config:/etc/letsencrypt
      - ${APP_VOLUME}/certbot/data:/var/lib/letsencrypt
      - ${APP_VOLUME}/certbot/scripts:/opt/scripts
    ports:
      - "8082:80"
      - "9443:443"
    command: "certonly --agree-tos --dns-digitalocean --dns-digitalocean-credentials /etc/letsencrypt/do.ini --cert-name wildcard-home-amer-dev -d \"*.${WEB_DOMAIN}\" -d \"${WEB_DOMAIN}\""
