version: "3.9"
name: media-stack
services:

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest

    networks:
      servarr:

    ports:
      - 9696:9696

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ${PROWLARR_CONFIG}:/config

    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd

    networks:
      servarr:

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST

    ports:
      - 8080:8080

    volumes:
      - ${SABNZBD_CONFIG}:/config
      - ${USENET_DOWNLOADS}:/downloads
      - ${USENET_DOWNLOADS_INCOMPLETE}:/incomplete-downloads


    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest

    networks:
      servarr:

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST

    ports:
      - 7878:7878

    volumes:
      - ${RADARR_CONFIG}:/config
      - ${MOVIES_FOLDER}:/movies
      - ${USENET_DOWNLOADS}:/downloads

    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr

    networks:
      servarr:

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST

    volumes:
      - ${SONARR_CONFIG}:/config
      - ${TV_FOLDER}:/tv
      - ${USENET_DOWNLOADS}:/downloads

    ports:
      - 8989:8989

    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ${READARR_CONFIG}:/config
      - ${BOOKS_FOLDER}:/books
      - ${USENET_DOWNLOADS}:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      servarr:


  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    runtime: nvidia

    networks:
      - servarr

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - JELLYFIN_PublishedServerUrl=$JELLYFIN_URL
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${MOVIES_FOLDER}:/movies
      - ${TV_FOLDER}:/tv

    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920

    restart: unless-stopped

  dns:
    build:
      context: ./dns/
      dockerfile: Dockerfile
    image: media-server-dns
    container_name: dns

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx

    volumes:
      - ${CERT_FOLDER}:/etc/letsencrypt
      - ${NGINX_FOLDER}:/etc/nginx/conf.d/

    ports:
      - 80:80
      - 443:443

    networks:
      - servarr

    restart: "unless-stopped"
  
  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile

    image: media-server-certbot
    container_name: certbot

    env_file: .env

    volumes:
      - ${CERT_FOLDER}:/etc/letsencrypt

    networks:
      - servarr

    restart: "unless-stopped"

networks:
  servarr:
    external: true
